package Collective;



public class Melee extends Minion {
    enum MeleeTypes{
        SHAMSHIRZANEFARS,ASBSAVAREFARS,PAHLAVANEFARS,SEPAHSALAREFARS,
        JASOOSETOORANI,GORZDARETOORANI,SHAHZADEYETOORANI,DIVEGORAZSAVAR,
        SHIREDARANDE,GORGESEFID,PALANG,GORG,GORAZEVAHSHI,PIRAN,BAHMAN,
        ASHKBOOS,GHOOLEDOSAR,FOOLADZERE,SIAVASH,SHAHGHOOL,ARZHANGDIV;
    }
    public void attack(){}
}
