package Collective;

enum MeleeTypes{
    SHAMSHIRZANEFARS,ASBSAVAREFARS,PAHLAVANEFARS,SEPAHSALAREFARS,
    JASOOSETOORANI,GORZDARETOORANI,SHAHZADEYETOORANI,DIVEGORAZSAVAR,
    SHIREDARANDE,GORGESEFID,PALANG,GORG,GORAZEVAHSHI,PIRAN,BAHMAN,
    ASHKBOOS,GHOOLEDOSAR,FOOLADZERE,SIAVASH,SHAHGHOOL,ARZHANGDIV;
}

public class Melee extends Minion {

    public void attack(){}
}
