package Collective;

enum RangedTypes{
    KAMANDAREFARS,KAMANDARETOORANI,GHOLLABSANGDARETOORANI,
    GHOOLETAKCHESHM,OGHAB,MARESAMMI,EZHDEHAYEATASHANDAZ,
    MAREGHOOLPEIKAR,JADOOGAR,JADOOGAREAZAM,JEN,GIV,IRAJ,NANESARMA;

}

public class Ranged extends Minion {

    public void attack(){}
}
